### ISSUE TITLE
compatible issue with python 3.12 and above

### ISSUE THREAD

**Issue by zero-custom** [aprilahijriyan/certpy#1]
I'm experiencing a compatible issue on Python 3.12+. The certpy failed to run, and display this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/certpy", line 5, in <module>
    from certpy.__main__ import cli
  File "/usr/local/lib/python3.13/site-packages/certpy/__main__.py", line 2, in <module>
    from distutils.dir_util import remove_tree
ModuleNotFoundError: No module named 'distutils'
```

**Comment by aprilahijriyan** [comment]
hi @zero-custom
Sorry for the late response. I have uploaded the latest version for compatibility with version 3.12+.
